<?php
/**
 *
 * Based on Piwik Extension for Magento created by Adrian Speyer
 *
 * @category    Matomo
 * @package     Matomo_Analytics
 * @copyright   Copyright (c) 2018 Thiago Contardi.
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 *
 */
/** @var Matomo_Analytics_Block_Script $this */
?>
<?php if (! $this->helper('core/cookie')->isUserNotAllowSaveCookie() && $this->getSiteId()): ?>
    <!-- Matomo -->
    <script>
        var _paq = window._paq = window._paq || [];
        (function () {
            var u = "<?php echo $this->getInstallPath() ?>";
            _paq.push(['setSiteId', <?php echo $this->getSiteId() ?>]);
            _paq.push(['setTrackerUrl', u + 'matomo.php']);

            <?php echo $this->getEcommerceCartUpdate() ?>
            <?php echo $this->getOrdersTrackingCode() ?>
            <?php echo $this->getProductPageview() ?>
            <?php echo $this->getCategoryPageview() ?>

            <?php if ($this->getSearchResultCount() > 0): ?>
                _paq.push(['setCustomUrl', '' + document.URL + '&search_count=<?php echo $this->getSearchResultCount() ?>']);
            <?php endif ?>

            <?php if ($this->is404()): ?>
                _paq.push(['setDocumentTitle', '404/URL = ' + String(document.location.pathname + document.location.search).replace(/\//g, "%2f") + '/From = ' + String(document.referrer).replace(/\//g, "%2f")]);
            <?php endif ?>

            _paq.push(['trackPageView']);
            _paq.push(['enableLinkTracking']);
            var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
            g.async = true; g.src = u + 'matomo.js'; s.parentNode.insertBefore(g, s);
        })();
    </script>
    <noscript><p><img src="<?php echo $this->getInstallPath() ?>matomo.php?idsite=<?php echo $this->getSiteId() ?>&rec=1" style="border:0" alt="" /></p></noscript>
    <!-- End Matomo Code -->
<?php endif ?>
