<?php
/**
 *
 * Based on Piwik Extension for Magento created by Adrian Speyer
 *
 * @category    Matomo
 * @package     Matomo_Analytics
 * @copyright   Copyright (c) 2018 Thiago Contardi.
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 *
 */
/** @var Matomo_Analytics_Block_Script $this */
?>
<?php if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>

    <?php
    $siteId = Mage::getStoreConfig(Matomo_Analytics_Helper_Data::XML_PATH_SITE);
    $installPath = Mage::getStoreConfig(Matomo_Analytics_Helper_Data::XML_PATH_INSTALL);
    $action = Mage::app()->getRequest()->getActionName();

    if ($siteId): ?>

        <?php
        /*remove https or https*/
        $installPath = preg_replace('/^https?:/', '', $installPath);

        // 0 Search Results
        if ($this->getRequest()->getControllerName() == 'result') {
            $queryText = Mage::helper('catalogsearch')->getQuery()->getQueryText();
            $noRes = Mage::helper('catalogsearch')->getEngine()
                ->getResultCollection()
                ->addSearchFilter($queryText)
                ->getSize();
        }
        ?>

        <!-- START PIWIK TRACKING CODE -->
        <script type="text/javascript">
            //<![CDATA[
            var _paq = _paq || [];
            (function () {
                var u = "<?php echo $installPath ?>";
                _paq.push(['setSiteId', <?php echo $siteId ?>]);
                _paq.push(['setTrackerUrl', u + 'piwik.php']);

                <?php echo $this->getEcommerceCartUpdate()?>
                <?php echo $this->getOrdersTrackingCode()?>
                <?php echo $this->getProductPageview()?>
                <?php echo $this->getCategoryPageview()?>

                <?php if (isset($noRes)): ?>
                    _paq.push(['setCustomUrl', '' + document.URL + '&search_count=<?php echo $noRes ?>']);
                <?php endif ?>

                <?php
                //404
                if ($action == 'noRoute'): ?>
                    _paq.push(['setDocumentTitle', '404/URL = ' + String(document.location.pathname + document.location.search).replace(/\//g, "%2f") + '/From = ' + String(document.referrer).replace(/\//g, "%2f")]);
                <?php endif; ?>

                _paq.push(['trackPageView']);
                _paq.push(['enableLinkTracking']);
                var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
                g.type = 'text/javascript';
                g.defer = true;
                g.async = true;
                g.src = u + 'piwik.js';
                s.parentNode.insertBefore(g, s);
            })();
        </script>
        <noscript>
            <p><img src="<?php echo $installPath ?>piwik.php?idsite=<?php echo $siteId ?>" style="border:0" /></p>
        </noscript>
        <!-- END PIWIK TRACKING CODE -->

    <?php endif; ?>
<?php endif; ?>
